# 2.3 - TRATAMENTO DE EXCE√á√ïES E OUTRAS OPERA√á√ïES

# Conceito de exce√ß√µes

## Tratamento de exce√ß√µes

Quando trabalhamos com arquivos, √© comum encontrarmos alguns problemas, como arquivo inexistente e falta de permiss√£o para escrever em um. A maioria desses problemas s√≥ pode ser detectada durante a execu√ß√£o do programa. Quando uma falha inesperada ocorre e o interpretador n√£o consegue resolver o problema, dizemos que houve uma exce√ß√£o.

Nesses casos, precisamos informar ao interpretador como tratar a exce√ß√£o, para que o programa n√£o seja interrompido. Se a exce√ß√£o √© um problema inesperado, como trat√°-la? Ao desenvolver um programa, precisamos procurar na documenta√ß√£o da biblioteca, do m√≥dulo ou da pr√≥pria linguagem de programa√ß√£o se as funcionalidades que vamos utilizar t√™m exce√ß√µes mapeadas. Essas exce√ß√µes s√£o problemas que podem ocorrer, e √© nossa tarefa trat√°-las.

> ‚ùì Voc√™ deve estar se perguntando: ‚ÄúO que seria ‚Äòtratar uma exce√ß√£o?‚Äù. Isso nada mais √© do que dizer ao Python o que fazer, ou quais instru√ß√µes executar, quando ele encontrar um problema.
> 

Tratar uma exce√ß√£o significa lidar com um erro ou situa√ß√£o inesperada que pode ocorrer durante a execu√ß√£o de um programa. Quando uma exce√ß√£o √© levantada em um programa, o programa interrompe sua execu√ß√£o normal e tenta encontrar um bloco de c√≥digo que possa lidar com a exce√ß√£o. Isso √© importante para garantir que o programa continue a ser executado mesmo quando ocorrerem erros, evitando que ele quebre de forma inesperada.

Para ilustrar, observe os seguintes passos:

1. Quando abrimos um arquivo em modo leitura e esse arquivo n√£o existe, o Python lan√ßa uma exce√ß√£o do tipo FileNotFoundError.

2. Se¬†**n√£o**¬†avisarmos ao Python o que fazer quando isso ocorrer, o programa ser√° interrompido.

3. Nesse caso, um tratamento para essa exce√ß√£o poderia ser: exibir um pop-up ao usu√°rio informando que o arquivo n√£o existe.


üó®Ô∏è Existem diversas formas de tratar exce√ß√µes em Python, como a utiliza√ß√£o de blocos try-except para capturar exce√ß√µes espec√≠ficas e realizar a√ß√µes para lidar com elas, ou a utiliza√ß√£o do bloco finally para executar a√ß√µes que devem ser realizadas independentemente de ter ocorrido uma exce√ß√£o ou n√£o.



### Mas o que acontece quando uma exce√ß√£o lan√ßada n√£o √© tratada?

Ela interrompe a execu√ß√£o normal do programa e uma mensagem de erro √© exibida no console. Essa mensagem cont√©m informa√ß√µes sobre o tipo de exce√ß√£o que ocorreu e a linha de c√≥digo onde ela aconteceu. Se a exce√ß√£o n√£o for tratada, o programa ir√° parar de executar e o usu√°rio poder√° ter dificuldades para entender o que aconteceu e como corrigir o problema. 

Al√©m disso, se o programa n√£o estiver em um ambiente de desenvolvimento, a mensagem de erro pode n√£o ser vis√≠vel para o usu√°rio final e o programa pode simplesmente travar ou fechar inesperadamente.

Para resolver isso, precisamos tratar a exce√ß√£o, ou melhor, uma poss√≠vel exce√ß√£o. Esse tratamento informa ao Python uma rota alternativa, caso ele encontre um problema.

> Para tratar exce√ß√µes, precisamos ‚Äúenvolver‚Äù o trecho de c√≥digo pass√≠vel de erro com a cl√°usula try/except ou try/except/finally. Veremos apenas a cl√°usula try/except. Essa estrutura permite que um trecho de c√≥digo seja executado normalmente at√© que ocorra uma exce√ß√£o, que ser√° capturada e tratada no bloco **`except`**.
> 

```python
try:
    x = int(input("Digite um n√∫mero: "))
    y = int(input("Digite outro n√∫mero: "))
    resultado = x / y
    print(f"O resultado da divis√£o √©: {resultado}")
except ZeroDivisionError:
    print("N√£o √© poss√≠vel dividir por zero")
except ValueError:
    print("Digite apenas n√∫meros inteiros")
```

Ao usar o **`try-except`**, o programa tenta executar o bloco de c√≥digo dentro do **`try`**. Se ocorrer uma exce√ß√£o, o programa captura a exce√ß√£o e executa o bloco **`except`** correspondente. No exemplo acima, se o usu√°rio tentar dividir por zero, o programa exibir√° a mensagem "N√£o √© poss√≠vel dividir por zero" em vez de gerar um erro e parar a execu√ß√£o. Se o usu√°rio digitar um valor inv√°lido, como uma letra, o programa exibir√° a mensagem "Digite apenas n√∫meros inteiros".

Dessa forma, com o tratamento de exce√ß√µes, podemos evitar que o programa pare de funcionar de forma inesperada e podemos fornecer uma mensagem mais clara e compreens√≠vel para o usu√°rio. Praticamente todas as exce√ß√µes em Python s√£o herdadas da classe¬†*Exception*, ou seja, ela √© uma exce√ß√£o muito gen√©rica, lan√ßada por diversos tipos de erros diferentes. Quanto mais gen√©rica, mais abrangente √© a exce√ß√£o.


‚ö†Ô∏è **Aten√ß√£o!**

N√£o √© uma boa pr√°tica utilizar exce√ß√µes abrangentes, pois elas podem silenciar erros que n√£o esperamos. O ideal √© tratar as exce√ß√µes utilizando a forma mais espec√≠fica poss√≠vel.



Confira algumas exce√ß√µes espec√≠ficas relacionadas √† manipula√ß√£o de arquivos e alguns motivos que podem gerar essas exce√ß√µes:

- **PermissionError**
    
    Lan√ßada quando n√£o temos permiss√£o para realizar uma opera√ß√£o.
    
- **FileExistsError**
    
    Lan√ßada quando tentamos criar um arquivo ou diret√≥rio j√° existentes.
    
- **FileNotFoundError**
    
    Lan√ßada quando tentamos abrir um arquivo ou diret√≥rio que n√£o existem.
    

**Todas essas exce√ß√µes herdam da exce√ß√£o mais abrangente OSError, que, por sua vez, herda de¬†*Exception.***

Saiba que o Python s√≥ consegue tratar a exce√ß√£o caso o erro esteja mapeado em algum¬†*except*. Se o interpretador n√£o encontrar o¬†*except*¬†adequado, ser√° gerado um erro, e o programa ser√° interrompido.

Um problema cl√°ssico que ocorre quando lidamos com arquivos √© tentar alterar o conte√∫do de um arquivo quando ele est√° aberto em outro programa. No caso do sistema operacional Windows 10, √© lan√ßada uma exce√ß√£o sobre permiss√£o de acesso.


‚ö†Ô∏è **O Python direciona o fluxo de execu√ß√£o para o trecho onde √© realizado o tratamento da exce√ß√£o lan√ßada.**



## Opera√ß√µes adicionais em arquivos

Al√©m das op√ß√µes para leitura e escrita em arquivos, o Python disponibiliza um conjunto de opera√ß√µes adicionais, como renomear e apagar arquivo, al√©m de opera√ß√µes em diret√≥rios, como listar arquivos de diret√≥rios, criar diret√≥rios etc. A partir de agora, apresentaremos algumas dessas opera√ß√µes.

Vamos iniciar pela opera√ß√£o de remover um arquivo, que est√° dispon√≠vel por meio da fun√ß√£o¬†**remove**¬†do m√≥dulo¬†**os**¬†do Python.

A fun√ß√£o¬†**remove**¬†tem a seguinte sintaxe: `os.remove(caminho)`

### Exemplos

1. Renomeando um arquivo:
    
    ```python
    import os
    
    try:
        # Renomeando um arquivo
        os.rename('arquivo_antigo.txt', 'arquivo_novo.txt')
    except FileNotFoundError:
        print("Arquivo n√£o encontrado!")
    except FileExistsError:
        print("O arquivo novo j√° existe!")
    except Exception as e:
        print(f"Erro inesperado: {e}")
    ```
    
2. Apagando um arquivo:
    
    ```python
    import os
    
    try:
        # Apagando um arquivo
        os.remove('arquivo_a_ser_removido.txt')
    except FileNotFoundError:
        print("Arquivo n√£o encontrado!")
    except Exception as e:
        print(f"Erro inesperado: {e}")
    ```
    
3. Listando arquivos de um diret√≥rio:
    
    ```python
    import os
    
    try:
        # Listando arquivos de um diret√≥rio
        diretorio = './meu_diretorio'
        for nome_arquivo in os.listdir(diretorio):
            print(nome_arquivo)
    except FileNotFoundError:
        print("Diret√≥rio n√£o encontrado!")
    except Exception as e:
        print(f"Erro inesperado: {e}")
    ```
    
4. Criando um novo diret√≥rio:
    
    ```python
    import os
    
    try:
        # Criando um novo diret√≥rio
        os.mkdir('novo_diretorio')
    except FileExistsError:
        print("O diret√≥rio j√° existe!")
    except Exception as e:
        print(f"Erro inesperado: {e}")
    ```
    
5. Removendo um diret√≥rio:
    
    ```python
    import os
    
    try:
        # Removendo um diret√≥rio
        os.rmdir('diretorio_a_ser_removido')
    except FileNotFoundError:
        print("Diret√≥rio n√£o encontrado!")
    except Exception as e:
        print(f"Erro inesperado: {e}")
    ```
    
    
    üí° **Dica**
    
    Para os casos em que desejamos renomear sobrescrevendo o arquivo destino, caso ele exista, podemos utilizar a fun√ß√£o¬†*replace*, tamb√©m do m√≥dulo os.
    
    
    

---

# Manipula√ß√£o de diret√≥rios

## Criando e removendo diret√≥rios

Trabalhar com arquivos significa trabalhar com diret√≥rios. Vejamos as principais funcionalidades relacionadas √† manipula√ß√£o de diret√≥rios em Python come√ßando pela cria√ß√£o e remo√ß√£o de um diret√≥rio.

Para criar um diret√≥rio, utilizamos a fun√ß√£o mkdir do m√≥dulo os, enquanto, para remover um diret√≥rio, utilizamos a fun√ß√£o rmdir, tamb√©m do m√≥dulo¬†**os**.

A sintaxe dessas duas fun√ß√µes s√£o as seguintes: 

`os.mkdir(caminho)`

`os.rmdir(caminho)`

### Exemplos:

Exemplo de cria√ß√£o de um diret√≥rio com a fun√ß√£o **`mkdir`**:

```python
import os

# criando um diret√≥rio chamado "exemplo"
os.mkdir("exemplo")
```

- Caso n√£o tenhamos permiss√£o para criar o diret√≥rio, ser√° lan√ßada a exce√ß√£o¬†**PermissionError**.
- Caso o diret√≥rio j√° exista, a exce√ß√£o¬†**FileExistsError**¬†√© lan√ßada.

---

Exemplo de remo√ß√£o de um diret√≥rio com a fun√ß√£o **`rmdir`**:

```python
import os

# removendo o diret√≥rio "exemplo"
os.rmdir("exemplo")
```

Para os casos em que o diret√≥rio a ser removido n√£o esteja vazio, ser√° lan√ßada a exce√ß√£o OSError. Essa exce√ß√£o √© mais abrangente. N√£o temos como garantir, a princ√≠pio, que a exce√ß√£o lan√ßada ocorre especificamente pelo fato de o diret√≥rio n√£o estar vazio. Nessas situa√ß√µes, precisamos analisar mais o erro, principalmente o seu n√∫mero, para verificar o que realmente aconteceu. O n√∫mero do erro est√° dispon√≠vel no atributo errno do objeto erro. 

Os c√≥digos dos poss√≠veis erros est√£o no m√≥dulo errno do Python e podem ser utilizados no tratamento das exce√ß√µes para descobrir o que realmente deu errado. Como a exce√ß√£o OSError √© mais abrangente que as outras exce√ß√µes que estudamos, ela deve ficar por √∫ltimo. Caso contr√°rio, nunca alcan√ßaremos as exce√ß√µes mais espec√≠ficas.

```python
import os
import errno

try:
    os.rmdir('meu_diretorio')
except OSError as e:
    if e.errno == errno.ENOTEMPTY:
        print("O diret√≥rio n√£o est√° vazio.")
    else:
        print(f"Ocorreu um erro inesperado: {e}")
```

√â importante lembrar que a fun√ß√£o **`rmdir`** s√≥ pode ser utilizada para remover diret√≥rios vazios. Caso o diret√≥rio contenha arquivos ou subdiret√≥rios, √© necess√°rio utilizar a fun√ß√£o **`rmtree`** do m√≥dulo shutil para remover o diret√≥rio e todo o seu conte√∫do:

```python
import shutil

# removendo o diret√≥rio "exemplo" e todo o seu conte√∫do
shutil.rmtree("exemplo")
```

## Listando conte√∫do de diret√≥rios

Outra tarefa muito comum quando estamos tratando com arquivos √© listar os arquivos presentes em um diret√≥rio.

Para isso, podemos utilizar a fun√ß√£o scandir do m√≥dulo os. Sua sintaxe √© a seguinte:

`os.scandir(caminho)`

Nesse exemplo, temos o nome do m√≥dulo¬†**os**, seguido de um ponto e o nome da fun√ß√£o scandir. Como par√¢metro, a fun√ß√£o espera o caminho para o¬†**diret√≥rio**.

Como resultado, teremos um iter√°vel (iterator) que retorna objetos do tipo os.DirEntry, que podem ser arquivos ou diret√≥rios. Dentre os atributos e m√©todos desse tipo de objetos, destacamos:

`Name`: Nome do diret√≥rio ou arquivo.

`Path`: Caminho completo do diret√≥rio ou arquivo.

`is_dir()`: Retorna verdadeiro se o objeto √© um diret√≥rio.

`is_file()`: Retorna verdadeiro se o objeto √© um arquivo.

`stat()`: Retorna alguns atributos do arquivo ou diret√≥rio, como tamanho.